### ISSUE TITLE
Max recursion reached

### ISSUE THREAD

**Issue by damianburrin** [shaoziyang/microbit-lib#4]
When I call the getAltitude function I get a runtime error for maximum recursion.

Any help greatly appreciated
![capture](https://user-images.githubusercontent.com/18092613/47877932-0129db80-de15-11e8-9120-faaa16fd2023.JPG)

**Comment by shaoziyang** [comment]
It may cause by new micropython 1.0 recursion limit, I will do more test late.

You may modify bmp180.py as below momentarily.

class BMP180():
    ...
    ...

    # Calculating absolute altitude
    def getAltitude(self):
        self.get()
        return 44330*(1-(self.P()/101325)**(1/5.255))

**Comment by damianburrin** [comment]
Thank you
